DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS warehouses CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS logs CASCADE;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR UNIQUE,
  password VARCHAR,
  role VARCHAR(10),
  status VARCHAR(10),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL,
  recent_login_at TIMESTAMP DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE warehouses (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR UNIQUE,
   location VARCHAR,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT NULL,
   PRIMARY KEY (id)
);

CREATE TABLE items (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
   warehouse_id BIGINT,
   name VARCHAR UNIQUE,
   price INTEGER NOT NULL,
   quantity INTEGER NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT NULL,
   PRIMARY KEY (id),
   CONSTRAINT fk_warehouse FOREIGN KEY (warehouse_id)
                              REFERENCES warehouses(id)
                              ON DELETE SET NULL
);

CREATE TABLE logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR,
    url TEXT,
    method TEXT,
    parameters TEXT,
    status VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_logs_created_at ON logs (created_at);
CREATE INDEX idx_logs_status ON logs (status);
CREATE INDEX idx_logs_status_created_at ON logs (status, created_at);
