DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS warehouses CASCADE;

CREATE TABLE users (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      username VARCHAR UNIQUE,
                      password VARCHAR,
                      role VARCHAR(10),
                      status VARCHAR(10),
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT NULL,
                      recent_login_at TIMESTAMP DEFAULT NULL,
                      PRIMARY KEY (id)
);

CREATE TABLE warehouses (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR UNIQUE,
                       location VARCHAR,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT NULL,
                       PRIMARY KEY (id)
);