DROP TABLE IF EXISTS user CASCADE;

CREATE TABLE user (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      username VARCHAR(10),
                      password VARCHAR(100),
                      role VARCHAR(10),
                      PRIMARY KEY (id)
);
