DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      username VARCHAR(10),
                      password VARCHAR(100),
                      role VARCHAR(10),
                      created_at TIMESTAMP,
                      updated_at TIMESTAMP,
                      PRIMARY KEY (id)
);
